
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Fri Mar 27 19:41:35 CET 2020
//----------------------------------------------------

package cvetkovic.parser;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int DELIMITER = 33;
  public static final int GREATER_OR_EQUAL = 25;
  public static final int INCREMENT = 31;
  public static final int CHAR = 44;
  public static final int CONST = 7;
  public static final int RIGHT_SQUARE_BRACKET = 39;
  public static final int NOT_EQUAL = 23;
  public static final int GREATER = 24;
  public static final int CONTINUE = 16;
  public static final int NUM_CONST = 42;
  public static final int LESS = 26;
  public static final int FOR = 14;
  public static final int DECREMENT = 32;
  public static final int LESS_OR_EQUAL = 27;
  public static final int COMMA = 34;
  public static final int CLASS = 4;
  public static final int LEFT_CURLY_BRACKET = 40;
  public static final int SUBTRACTION = 18;
  public static final int IF = 8;
  public static final int DOT = 35;
  public static final int LEFT_ROUND_BRACKET = 36;
  public static final int BOOLEAN = 45;
  public static final int ABSTRACT = 5;
  public static final int EOF = 0;
  public static final int RETURN = 12;
  public static final int EQUAL = 22;
  public static final int LOGICAL_OR = 29;
  public static final int LEFT_SQUARE_BRACKET = 38;
  public static final int NEW = 9;
  public static final int error = 1;
  public static final int PROGRAM = 2;
  public static final int MODULO = 21;
  public static final int IDENT = 43;
  public static final int BREAK = 3;
  public static final int VOID = 13;
  public static final int ASSINGMENT = 30;
  public static final int ELSE = 6;
  public static final int READ = 11;
  public static final int LOGICAL_AND = 28;
  public static final int ADDITION = 17;
  public static final int EXTENDS = 15;
  public static final int DIVISION = 20;
  public static final int RIGHT_CURLY_BRACKET = 41;
  public static final int MULTIPLICATION = 19;
  public static final int PRINT = 10;
  public static final int RIGHT_ROUND_BRACKET = 37;
}

